"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import secrets
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import dotenv_values

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Support both the documented `.env` file and the local `env` file in this repo.
# Precedence is: process environment > local `env` > `.env`.
dotenv_merged = {
    **dotenv_values(BASE_DIR / ".env"),
    **dotenv_values(BASE_DIR / "env"),
}
for _key, _value in dotenv_merged.items():
    if _value is not None:
        os.environ.setdefault(_key, _value)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

def _env_bool(value: str | None, default: bool = False) -> bool:
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "t", "yes", "y", "on"}


def _env_list(value: str | None) -> list[str]:
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


def _env_int(value: str | None, default: int | None = None) -> int | None:
    if value is None or not value.strip():
        return default
    return int(value.strip())


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool(os.getenv("DEBUG"), True)

# SECURITY WARNING: keep the secret key used in production secret!
_configured_secret_key = os.getenv("SECRET_KEY", "").strip()
if _configured_secret_key:
    SECRET_KEY = _configured_secret_key
elif DEBUG:
    SECRET_KEY = secrets.token_urlsafe(50)
else:
    raise ImproperlyConfigured("SECRET_KEY is required when DEBUG is false.")

ALLOWED_HOSTS = _env_list(os.getenv("ALLOWED_HOSTS"))
website_hostname = os.getenv("WEBSITE_HOSTNAME", "").strip()
is_azure_app_service = bool(website_hostname)
if website_hostname:
    ALLOWED_HOSTS = sorted(set(ALLOWED_HOSTS).union({website_hostname}))

if DEBUG:
    # Include common local development hosts (web + Android emulator).
    dev_hosts = {"localhost", "127.0.0.1", "[::1]", "10.0.2.2"}
    ALLOWED_HOSTS = sorted(set(ALLOWED_HOSTS).union(dev_hosts))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.postgres',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'corsheaders',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

_configured_cors_origins = _env_list(os.getenv("CORS_ALLOWED_ORIGINS"))
if DEBUG:
    _configured_cors_origins = list(
        sorted(set(_configured_cors_origins).union({"http://localhost:3000", "http://127.0.0.1:3000"}))
    )
CORS_ALLOWED_ORIGINS = _configured_cors_origins

FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://127.0.0.1:3000").rstrip("/")
_configured_csrf_origins = _env_list(os.getenv("CSRF_TRUSTED_ORIGINS"))
if FRONTEND_BASE_URL.startswith(("http://", "https://")):
    _configured_csrf_origins = list(sorted(set(_configured_csrf_origins).union({FRONTEND_BASE_URL})))
CSRF_TRUSTED_ORIGINS = _configured_csrf_origins

azure_secure_defaults = is_azure_app_service and not DEBUG
USE_X_FORWARDED_HOST = _env_bool(os.getenv("USE_X_FORWARDED_HOST"), azure_secure_defaults)
USE_SECURE_PROXY_SSL_HEADER = _env_bool(
    os.getenv("USE_SECURE_PROXY_SSL_HEADER"),
    azure_secure_defaults,
)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if USE_SECURE_PROXY_SSL_HEADER else None
SECURE_SSL_REDIRECT = _env_bool(os.getenv("SECURE_SSL_REDIRECT"), azure_secure_defaults)
SESSION_COOKIE_SECURE = _env_bool(os.getenv("SESSION_COOKIE_SECURE"), azure_secure_defaults)
CSRF_COOKIE_SECURE = _env_bool(os.getenv("CSRF_COOKIE_SECURE"), azure_secure_defaults)
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "3600" if azure_secure_defaults else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
    os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS"),
    False,
)
SECURE_HSTS_PRELOAD = _env_bool(os.getenv("SECURE_HSTS_PRELOAD"), False)
SECURE_REFERRER_POLICY = os.getenv("SECURE_REFERRER_POLICY", "same-origin")

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    raise ImproperlyConfigured("DATABASE_URL is required to configure the database.")

DATABASES = {
    "default": dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
    )
}

# In production we require PostgreSQL; allow sqlite only during Docker build.
if (
    DATABASES["default"].get("ENGINE") != "django.db.backends.postgresql"
    and not DATABASE_URL.startswith("sqlite")
):
    raise ImproperlyConfigured(
        "DATABASE_URL must use PostgreSQL (postgresql:// or postgres://)."
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "api.User"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Toronto'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = BASE_DIR / "media"

AZURE_CONNECTION_STRING = os.getenv("AZURE_CONNECTION_STRING", "").strip()
AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME", "").strip()
AZURE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY", "").strip()
AZURE_SAS_TOKEN = os.getenv("AZURE_SAS_TOKEN", "").strip()
AZURE_MEDIA_CONTAINER = os.getenv("AZURE_MEDIA_CONTAINER", "media").strip()
AZURE_MEDIA_LOCATION = os.getenv("AZURE_MEDIA_LOCATION", "").strip().strip("/")
AZURE_MEDIA_CUSTOM_DOMAIN = os.getenv("AZURE_MEDIA_CUSTOM_DOMAIN", "").strip()
AZURE_MEDIA_URL_EXPIRATION_SECS = _env_int(os.getenv("AZURE_MEDIA_URL_EXPIRATION_SECS"))
AZURE_MEDIA_OVERWRITE_FILES = _env_bool(os.getenv("AZURE_MEDIA_OVERWRITE_FILES"), False)

USE_AZURE_MEDIA_STORAGE = bool(
    AZURE_CONNECTION_STRING or (AZURE_ACCOUNT_NAME and (AZURE_ACCOUNT_KEY or AZURE_SAS_TOKEN))
)
SERVE_LOCAL_MEDIA_FILES = not USE_AZURE_MEDIA_STORAGE

if USE_AZURE_MEDIA_STORAGE and not AZURE_MEDIA_CONTAINER:
    raise ImproperlyConfigured("AZURE_MEDIA_CONTAINER is required when Azure media storage is enabled.")

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": str(MEDIA_ROOT),
            "base_url": MEDIA_URL,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if USE_AZURE_MEDIA_STORAGE:
    azure_media_options: dict[str, object] = {
        "azure_container": AZURE_MEDIA_CONTAINER,
        "overwrite_files": AZURE_MEDIA_OVERWRITE_FILES,
    }
    if AZURE_CONNECTION_STRING:
        azure_media_options["connection_string"] = AZURE_CONNECTION_STRING
    else:
        azure_media_options["account_name"] = AZURE_ACCOUNT_NAME
        if AZURE_ACCOUNT_KEY:
            azure_media_options["account_key"] = AZURE_ACCOUNT_KEY
        if AZURE_SAS_TOKEN:
            azure_media_options["sas_token"] = AZURE_SAS_TOKEN
    if AZURE_MEDIA_LOCATION:
        azure_media_options["location"] = AZURE_MEDIA_LOCATION
    if AZURE_MEDIA_CUSTOM_DOMAIN:
        azure_media_options["custom_domain"] = AZURE_MEDIA_CUSTOM_DOMAIN
    if AZURE_MEDIA_URL_EXPIRATION_SECS is not None:
        azure_media_options["expiration_secs"] = AZURE_MEDIA_URL_EXPIRATION_SECS

    STORAGES["default"] = {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": azure_media_options,
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

from datetime import timedelta as _td  # noqa: E402
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': _td(hours=1),
    'REFRESH_TOKEN_LIFETIME': _td(days=1),
    'SIGNING_KEY': os.getenv("JWT_SECRET_KEY", SECRET_KEY),
}

BUSINESS_NAME = os.getenv("BUSINESS_NAME", "BrazWebDes Hairstylist Booking")
BUSINESS_ADDRESS = os.getenv("BUSINESS_ADDRESS", "230 Woolner Avenue, Toronto, ON")
BUSINESS_PHONE = os.getenv("BUSINESS_PHONE", "")
BOOKING_REPLY_TO = os.getenv("BOOKING_REPLY_TO", "").strip()
RESEND_API_KEY = os.getenv("RESEND_API_KEY", "").strip()
RESEND_FROM_EMAIL = os.getenv("RESEND_FROM_EMAIL", "").strip()
RESEND_OWNER_EMAIL = os.getenv("RESEND_OWNER_EMAIL", "").strip()
RESEND_WEBHOOK_SECRET = os.getenv("RESEND_WEBHOOK_SECRET", "").strip()
BOOKING_EMAILS_ENABLED = _env_bool(
    os.getenv("BOOKING_EMAILS_ENABLED"),
    bool(RESEND_API_KEY and RESEND_FROM_EMAIL and RESEND_OWNER_EMAIL),
)
